dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - AIOHTTP="3"
matrix:
  allow_failures:
    - python: "3.7"
install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`-aiohttp$AIOHTTP
  - echo "$TOXENV"

  - tox
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
