dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - AIOHTTP="2"
  - AIOHTTP="1"
install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`-aiohttp$AIOHTTP
  - echo "$TOXENV"

  - tox
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
